# Generated by Django 4.2.1 on 2023-05-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='vat_category',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='products.vat'),
        ),
    ]
