# Generated by Django 4.2.1 on 2023-05-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_vat_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vat_category',
            new_name='tax_category',
        ),
    ]
