# Generated by Django 4.2.1 on 2023-05-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_vat_category_product_tax_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
