# Generated by Django 4.2.1 on 2023-05-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_alt_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='PriceCategory',
        ),
    ]
