# Generated by Django 4.2.1 on 2023-05-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_vat_product_vat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.vat'),
        ),
    ]
